
AWSTemplateFormatVersion: "2010-09-09"
Description: App Runner Template for NodeJS RestApi

Parameters:
  NodeJSAPIPort:
    Type: Number
    Description: The Port that NodeJS API listening on
    Default: 3070
    AllowedValues:
      - 3070
      - 3090
      - 3080
  GitHubBranch:
    Type: String
    Description: GitHub Branch you want to deploy
    Default: master
  Environment:
    Type: String
    Description: Environment to Deploy
  WelcomeMessage:
    Type: String
    Description: Welcome Message for the API

Resources:
  NodeJSRestAPI:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub RESTAPI-${Environment}nodejs
      SourceConfiguration:
        AuthenticationConfiguration:
          ConnectionArn: "arn:aws:apprunner:us-east-2:864227929192:connection/DemoConnection/aaec8e02677441bb9c22343ca394dadb"
        AutoDeploymentsEnabled: true
        CodeRepository:
          RepositoryUrl: "https://github.com/bbachi/prod-ready-node-rest-api.git"
          SourceCodeVersion:
            Type: BRANCH
            Value: !Ref GitHubBranch
          CodeConfiguration:
            ConfigurationSource: API
            CodeConfigurationValues:
              Runtime: NODEJS_12
              BuildCommand: "npm install && npm run build"
              StartCommand: "npm run prod"
              Port: !Ref NodeJSAPIPort
              RuntimeEnvironmentVariables:
                -
                  Name: API_WORKS_MESSAGE
                  Value: !Ref WelcomeMessage
      InstanceConfiguration:
        Cpu: 1 vCPU
        Memory: 2 GB
        
Outputs:
  AppRunnerServiceArn:
    Description: ServiceArn of GitHub
    Value: !GetAtt NodeJSRestAPI.ServiceArn
  AppRunnerServiceId:
    Description: AppRunnerServiceId
    Value: !GetAtt NodeJSRestAPI.ServiceId
  AppRunnerServiceUrl:
    Description: AppRunnerServiceUrl
    Value: !GetAtt NodeJSRestAPI.ServiceUrl

